export * from './modalBlog';
export * from './modalClass';
export * from './modalCurso';
export * from './modalTeacher';
export * from './modalAddStudent'
export * from './modalDiscipline'
export * from './modalCreateBlog'
export * from './modalToEndSession'
export * from './modalDisciplineTeacher'
export * from './modalUpdateDataUserProfile'